SRC_URI:append:netx4000 = " \
    file://netx4000/0001-arm-Add-basic-support-for-Hilscher-netX4000-SoC.patch      \
    file://netx4000/0002-pl011-Fix-invalid-byte-access-in-debug-mode.patch          \
    file://netx4000/0003-nbpfaxi-Add-netx4000-support-for-requesting-specific.patch \
    file://netx4000/0004-mmc-Add-SD-MMC-driver-for-Hilscher-netX4000-based-pl.patch \
    file://netx4000/0005-gpio-Add-GPIO-driver-for-Hilscher-netX4000-based-pla.patch \
    file://netx4000/0006-rtc-Add-RTC-driver-for-Hilscher-netX4000-based-platf.patch \
    file://netx4000/0007-i2c-Add-I2C-bus-driver-for-Hilscher-netX4000-based-p.patch \
    file://netx4000/0008-adc-Add-IIO-ADC-driver-for-Hilscher-netX4000-based-p.patch \
    file://netx4000/0009-usb-hcd-Add-USB-HCD-driver-for-Hilscher-netX4000-bas.patch \
    file://netx4000/0010-usb-udc-Add-USB-UDC-driver-for-Hilscher-netX4000-bas.patch \
    file://netx4000/0011-spi-Add-QSPI-driver-for-Hilscher-netX4000-based-plat.patch \
    file://netx4000/0012-fbdev-Add-Framebuffer-driver-for-Hilscher-netX4000-b.patch \
    file://netx4000/0013-edac-Add-EDAC-CACHE-DC-and-DDR-MC-driver-for-Hilsche.patch \
    file://netx4000/0014-can-Add-CAN-bus-driver-rza1_can-from-Renesas-with-ne.patch \
    file://netx4000/0015-of-Add-dt-overlay-configfs-interface-v2.patch              \
    file://netx4000/0016-pcie-netx4000-Add-pcie-root-complex-driver.patch           \
    file://netx4000/0017-eth-xc-stdmac-Add-standard-ethernet-MAC-driver-using.patch \
    file://netx4000/0018-uio_netx-Update-including-device-tree-support-with-n.patch \
    file://netx4000/0019-amba-pl011-Add-RS485-support-ioctl-and-devicetree.patch    \
    file://netx4000/0020-spidev-Add-spidev-compatible-string-to-silence-warni.patch \
"
