#!/bin/sh

rootfs_image_file_enabled() {
	return 0
}

rootfs_image_file_run() {
	if (echo $bootparam_root | grep -q "rootfs.img"); then
		image=$(basename $bootparam_root)
		dev=$(dirname $bootparam_root)
		part=$(basename $dev)

		if [ "$bootparam_rootwait" == "true" ]; then
			# waiting for root device
			debug "Waiting for root device $dev"
			while [ ! -b "$dev" ]; do sleep 1; done
		fi

		mkdir -p /media/$part
		mount $dev /media/$part

		bootparam_root="/media/$part/$image"
		bootparam_rootflags="sync"
		bootparam_rootwait=false
	fi
}
